/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sienna
 */
public class U1A4A3MakingPizza extends javax.swing.JFrame {

    /**
     * Creates new form U1A4A3MakingPizza
     */
    public U1A4A3MakingPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGrandtotal = new javax.swing.JLabel();
        lblTaxes = new javax.swing.JLabel();
        lblPizzaDia = new javax.swing.JLabel();
        txtPizzaDia = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        lblTaxesPrice = new javax.swing.JLabel();
        lblSubtotalPrice = new javax.swing.JLabel();
        lblGrandtotalPrice = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblOutputMsg = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        lblGrandtotal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGrandtotal.setText("Grandtotal:");
        lblGrandtotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTaxes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTaxes.setText("Taxes:");
        lblTaxes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPizzaDia.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lblPizzaDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPizzaDia.setText("Diameter of Pizza (CM):");
        lblPizzaDia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtPizzaDia.setBackground(new java.awt.Color(255, 255, 204));
        txtPizzaDia.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtPizzaDia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPizzaDia.setText("0.00 cm");
        txtPizzaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPizzaDiaActionPerformed(evt);
            }
        });

        lblSubtotal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSubtotal.setText("Subtotal:");
        lblSubtotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCalculate.setBackground(new java.awt.Color(255, 255, 204));
        btnCalculate.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCalculate.setText("Check Out");
        btnCalculate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblTaxesPrice.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTaxesPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaxesPrice.setText("$0.00");
        lblTaxesPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSubtotalPrice.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSubtotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtotalPrice.setText("$0.00");
        lblSubtotalPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblGrandtotalPrice.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblGrandtotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrandtotalPrice.setText("$0.00");
        lblGrandtotalPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sienna\\Downloads\\pizza_boy(1).png")); // NOI18N
        jLabel1.setText("jLabel1");

        lblOutputMsg.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        lblOutputMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutputMsg.setText("MmmMmm How's Your Pizza?");
        lblOutputMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addComponent(lblOutputMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(lblOutputMsg)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sienna's Putrid Pizza");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jSeparator1.setBackground(new java.awt.Color(255, 204, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblTaxes)
                                                    .addComponent(lblSubtotal)))
                                            .addComponent(lblGrandtotal))
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTaxesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSubtotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblGrandtotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPizzaDia)
                                        .addGap(0, 25, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(txtPizzaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(btnCalculate)))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPizzaDia)
                        .addGap(18, 18, 18)
                        .addComponent(txtPizzaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnCalculate)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotal)
                            .addComponent(lblSubtotalPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTaxes)
                            .addComponent(lblTaxesPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrandtotal)
                            .addComponent(lblGrandtotalPrice))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
    
    // variables required in the program
    double pizzaDia;
    final double priceLabour = 0.75;
    final double priceRent = 0.99;
    final double pricePerDia = 0.50;
    double subtotalLess15;
    double taxesLess15;
    double grandtotalLess15;
    double subtotalLess40;
    double taxesLess40;
    double grandtotalLess40;
    double subtotalBig40;
    double taxesBig40;
    double grandtotalBig40;
    
    // user enters the diameter of pizza  
    pizzaDia = Double.parseDouble(txtPizzaDia.getText());
    
    // possible choices based on the users pizza diameter size
    if (pizzaDia <= 15)
    {
    lblOutputMsg.setText("We are going to make you a cute little pizza!");
    subtotalLess15 = (pizzaDia * pricePerDia + priceRent + priceLabour);
    subtotalLess15 = Math.round(subtotalLess15 * 100.0) / 100.0;
    taxesLess15 = subtotalLess15 * 0.13;
    taxesLess15 = Math.round(taxesLess15 * 100.0) / 100.0;
    grandtotalLess15 = subtotalLess15 * 1.13;
    grandtotalLess15 = Math.round(grandtotalLess15 * 100.0) / 100.0;
    lblSubtotalPrice.setText(String.valueOf(subtotalLess15));
    lblTaxesPrice.setText(String.valueOf(taxesLess15));
    lblGrandtotalPrice.setText(String.valueOf(grandtotalLess15));
    }
    
    else if ((pizzaDia >= 20) && (pizzaDia <= 40))
    {
    lblOutputMsg.setText("This will be delicious!");
    subtotalLess40 = (pizzaDia * pricePerDia + priceRent + priceLabour);
    subtotalLess40 = Math.round(subtotalLess40 * 100.0) / 100.0;
    taxesLess40 = subtotalLess40 * 0.13;
    taxesLess40 = Math.round(taxesLess40 * 100.0) / 100.0;
    grandtotalLess40 = subtotalLess40 * 1.13;
    grandtotalLess40 = Math.round(grandtotalLess40 * 100.0) / 100.0;
    lblSubtotalPrice.setText(String.valueOf(subtotalLess40));
    lblTaxesPrice.setText(String.valueOf(taxesLess40));
    lblGrandtotalPrice.setText(String.valueOf(grandtotalLess40));
    }
    
    else if (pizzaDia > 40)
    {
    lblOutputMsg.setText("Whoa, big pizza! You might need a truck to get this home!");
    subtotalBig40 = (pizzaDia * pricePerDia + priceRent + priceLabour);
    subtotalBig40 = Math.round(subtotalBig40 * 100.0) / 100.0;
    taxesBig40 = subtotalBig40 * 0.13;
    taxesBig40 = Math.round(taxesBig40 * 100.0) / 100.0;
    grandtotalBig40 = subtotalBig40 * 1.13;
    grandtotalBig40 = Math.round(grandtotalBig40 * 100.0) / 100.0;
    lblSubtotalPrice.setText(String.valueOf(subtotalBig40));
    lblTaxesPrice.setText(String.valueOf(taxesBig40));
    lblGrandtotalPrice.setText(String.valueOf(grandtotalBig40));
    }
            
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtPizzaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPizzaDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPizzaDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U1A4A3MakingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U1A4A3MakingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U1A4A3MakingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U1A4A3MakingPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U1A4A3MakingPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGrandtotal;
    private javax.swing.JLabel lblGrandtotalPrice;
    private javax.swing.JLabel lblOutputMsg;
    private javax.swing.JLabel lblPizzaDia;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalPrice;
    private javax.swing.JLabel lblTaxes;
    private javax.swing.JLabel lblTaxesPrice;
    private javax.swing.JTextField txtPizzaDia;
    // End of variables declaration//GEN-END:variables
}
